project_id = "sclblrqylmzqvbjuegkq"

[functions.send-grundbuch-document]
verify_jwt = false

[functions.search-address]
verify_jwt = false

[functions.send-daily-order-report]
verify_jwt = false

[functions.get-orders]
verify_jwt = false

[functions.update-order]
verify_jwt = false