project_id = "sclblrqylmzqvbjuegkq"

[functions.send-grundbuch-document]
verify_jwt = false

[functions.search-address]
verify_jwt = false

[functions.send-daily-order-report]
verify_jwt = false

[functions.get-orders]
verify_jwt = false

[functions.update-order]
verify_jwt = false

[functions.get-order]
verify_jwt = false

[functions.bulk-update-orders]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.manage-webhooks]
verify_jwt = false

[functions.process-order]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.nominatim-lookup]
verify_jwt = false